[tool.poetry]
name = "repl_python3_beta_NoahJengtri3-2"
version = "0.1.0"
description = ""
authors = ["NoahJeng <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
mathpy = "^0.3.0"
patterns = "^0.3"
funcy = "^1.17"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
